import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/footer/Footer";
import { UserProvider } from "@/context/UserContext";
import CartButton from "@/components/buttons/CartButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Header />
          <NavBar />
          {children}
          <CartButton />
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
